### PR TITLE
Boolean prob

### LINKED ISSUE #42: Lemma names Prob.ge0 and prob_le0 are not uniform
`Prob.ge0` should be placed outside `Module Prob` and named `prob_ge0`.

### LINKED ISSUE #43: `prob` may have two eqType structures, leading to failures in rewriting / applying lemmas.
I experienced this issue when trying to use `prob_lt0`. The lemma takes as its argument `_ : p != 0` and it did not match my goal because of a mismatch between two `eqType` structures.

One solution would be to change the interface of `prob` to
```
Module Prob.
Record t := mk_ {
  p :> R ;
  Op1 : (0 <b= p <b= 1)%R }.
Definition O1 (p : t) : 0 <= p <= 1 :=
  match andP (Op1 p) with conj Op p1 => conj (leRP _ _ Op) (leRP _ _ p1) end.
Arguments O1 : simpl never.
Definition mk (q : R) (Oq1 : 0 <= q <= 1) : t.
Proof.
refine (@mk_ q (match Oq1 with conj Oq q1 => _ end)).
by move/leRP: Oq ->; move/leRP: q1 ->.
Defined.
Module Exports.
Notation prob := t.
Notation "q %:pr" := (@mk q (@O1 _)).
Canonical prob_subType := Eval hnf in [subType for p].
Definition prob_eqMixin := [eqMixin of prob by <:].
Canonical prob_eqType := Eval hnf in EqType _ prob_eqMixin.
End Exports.
End Prob.
Export Prob.Exports.
Coercion Prob.p : prob >-> R.
```

This seems to almost work, but failing at inferring the canonical structure for onem.

### PR DESCRIPTION
**Pull request by t6s**
Resolves #43

~(based on PR #47)~ has been merged

@t6s

### CODE REVIEW

**Comment by affeldt-aist** [comment]
Two things:
- it looks like the main change is to use (0 <b= p <b= 1)%R has the proof field for the prob structure, is this undersanding correct?
- before merging this PR we should move out of monae and in infotheo the pieces of code that expose the prob structure (this change has indeed exposed that we were lacking modularity here, this should be fixed beforehand)

**Comment by t6s** [comment]
> * it looks like the main change is to use (0 <b= p <b= 1)%R has the proof field for the prob structure, is this understanding correct? (one may wonder whether the lack of lra would be painful but since it is a proof inside a structure that should be ok)

Yes.

> * before merging this PR we should move out of monae and in infotheo the pieces of code that expose the prob structure (this change has indeed exposed that we were lacking modularity here, this should be fixed beforehand)

I did not understand this aspect very well.  Can you show by example what sort of changes should be made?

**Comment by affeldt-aist** [comment]
> > * before merging this PR we should move out of monae and in infotheo the pieces of code that expose the prob structure (this change has indeed exposed that we were lacking modularity here, this should be fixed beforehand)
> 
> I did not understand this aspect very well. Can you show by example what sort of changes should be made?

https://github.com/affeldt-aist/monae/pull/39/
already exposes where we reveal the Prob.mk constructor;
since only the proof field of `prob` has changed we could have expected
the change in infotheo to be more transparent.

I was also thinking of lemmas like
https://github.com/affeldt-aist/monae/blob/702b0be30a9e71b22fa84a884fd93d754c5a32c8/proba_lib.v#L298
that ought to be in infotheo in the first place.

At first sight, you seem to point at a lack of modularity.

**Comment by affeldt-aist** [comment]
@t6s how about we merge this now so that it does not block you?

**Comment by affeldt-aist** [comment]
maybe mkP is not good because it looks like a view; mk_ -> mk, mk -> build is maybe better @t6s

**Comment by t6s** [comment]
> maybe mkP is not good because it looks like a view; mk_ -> mk, mk -> build is maybe better @t6s

I would rather eliminate all uses of mk_. I partly did it in conv_set branch and it was not a big change.

**Comment by affeldt-aist** [comment]
> I would rather eliminate all uses of mk_. I partly did it in conv_set branch and it was not a big change.

In the interest of type, what about rolling back to mk_ and make an issue to treat all mk_'s removal later
once we have more material in master to evaluate it?

**Comment by t6s** [comment]
> > I would rather eliminate all uses of mk_. I partly did it in conv_set branch and it was not a big change.
> 
> In the interest of time, what about rolling back to mk_ and make an issue to treat all mk_'s removal later
> once we have more material in master to evaluate it?

No problem. Shall I file another PR to remove `mk_`?

**Comment by affeldt-aist** [comment]
> No problem. Shall I file another PR to remove `mk_`?

No hurry. For the time being, an issue will do. I'll fill one once this PR is merged.

**Pull request merged**
