### PR TITLE
upd opam

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by affeldt-aist** [comment]
@t6s @garrigue I don't get the CI error, you might have an idea

**Comment by t6s** [comment]
I tried to compile infotheo with coq-mathcomp-ssreflect.1.19.0 and failed.
There seems to be no algebra-tactics compatible to mc 1.19.0.

**Comment by t6s** [comment]
`  | (= "dev")  ` is bad?

**Comment by affeldt-aist** [comment]
it seems that the problem is no-algebra-tactics for 1.19 :-(
maybe it is just a matter of updating opam with more permissive bounds

**Comment by affeldt-aist** [comment]
> ` | (= "dev") ` is bad?

I think it is harmless.

**Comment by affeldt-aist** [comment]
Since infotheo seems to compile with analysis 0.7.0, I have in the meantime requested an opam update: https://github.com/coq/opam/pull/2929

**Comment by affeldt-aist** [comment]
> it seems that the problem is no-algebra-tactics for 1.19 :-( maybe it is just a matter of updating opam with more permissive bounds

e.g.: https://github.com/coq/opam/blob/master/released/packages/coq-mathcomp-algebra-tactics/coq-mathcomp-algebra-tactics.1.1.0/opam

**Comment by affeldt-aist** [comment]
Let's ask the developers: https://github.com/coq/opam/pull/2930

**Comment by affeldt-aist** [comment]
@t6s fixed by the opam fix!

**Pull request merged**
